apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: spring-boot
  namespace: default
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spring-boot
  targetCPUUtilizationPercentage: 50
