apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app
  namespace: default
  labels:
    app: redis-app
spec:
  selector:
    matchLabels:
      app: redis-app
  replicas: 1 # only 1
  template:
    metadata:
      labels:
        app: redis-app
    spec:
      containers:
        - name: redis-app
          image: redis:3.2.12
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379