apiVersion: apps/v1 # 1.19
kind: Deployment
metadata:
  name: spring-boot
spec:
  selector:
    matchLabels:
      app: spring
  replicas: 1
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - name: spring
          image: registry.cn-shanghai.aliyuncs.com/dockerhub2019/spring:0.0.2
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              value: redis-svc.default.svc.cluster.local
            - name: REDIS_PORT
              value: '6379'
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 30